### ISSUE TITLE
Compile and run applications in StormBenchmarks

### ISSUE THREAD

**Issue by alefais** [Xtra-Computing/briskstream#3]
Hi, I'm trying to compile and run your project and at the moment I'm able to compile it successfully. I'm trying to run the WordCount application in the StormBenchmarks sub-project but I'm having some problems. I tried both from the Linux shell and from Intellij IDEA in the following ways:

1. from the Linux shell:
    from the briskstream/StormBenchmarks directory I run

    `storm jar target/Storm-1.1.1-jar-with-dependencies.jar applications.StormRunner -a WordCount -m 
    local` 
    (where storm is the Storm command line client)

    but the following exceptions are thrown

    Exception in thread "main" java.lang.ExceptionInInitializerError
    ...
    Caused by: java.lang.RuntimeException: java.io.IOException: Found multiple defaults.yaml resources.
    You're probably bundling the Storm jars with your topology jar.

    [main] ERROR a.StormRunner - Unable to load configuration file: java.io.FileNotFoundException
    
2. from inside IntelliJ
    I set up StormRunner as the main class and I pass as program arguments `-a WordCount -m local`.
    The following exceptions are thrown

    java.io.FileNotFoundException: /Users/ale/data/app/wc/Skew01.dat (No such file or directory)
    [...]
    java.lang.NullPointerException: null
	at applications.spout.MemFileSpout.reset_index(MemFileSpout.java:211) ~[classes/:?]
	at applications.spout.MemFileSpout.nextTuple(MemFileSpout.java:220) ~[classes/:?]

Am I running the application in the wrong way?
Can you please help me in understanding what I'm doing wrong?

Thank you!

Alessandra

**Comment by ShuhaoZhangTony** [comment]
Hi!
Thanks for your interest.  
The first issue is a common issue for Storm. You need to compile the project with "mvn install -P cluster" to enable the cluster mode.
The second issue is about input data, which I didn't put into the repo as they are too large. You can use or generate your own datasets. Some of the datasets I used can be found here: https://github.com/mayconbordin/storm-applications.

B.R.
Tony
